# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new beta version"
  lane :beta do
    # sh "your_script.sh"
    # You can also use other beta testing services here
    upload_to_play_store(track: 'beta', apk: '../build/app/outputs/apk/production/release/app-production-release.apk')
  end

  desc "Submit a new internal version"
  lane :internal do
    # sh "your_script.sh"
    # You can also use other beta testing services here
    upload_to_play_store(track: 'internal', apk: '../build/app/outputs/apk/production/release/app-production-release.apk')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
